[package]
name = "based_on_piston_tutorial"
version = "0.1.0"
authors = ["Suyash Mohan <suyash@medzin.in>"]

[dependencies]
piston = "0.17.0"
pistoncore-glutin_window = "0.20.0"
piston2d-graphics = "0.13.0"
piston2d-opengl_graphics = "0.23.0"
